### ISSUE TITLE
Type declarations for us TypeScript folks?

### ISSUE THREAD

**Issue by connstructor** [xivapi/xivapi-js#15]
Attempting to use xivapi-js in a TypeScript project yields the following warning/error:

Could not find a declaration file for module 'xivapi-js'. [path]/node_modules/xivapi-js/XIVAPI.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/xivapi-js` if it exists or add a new declaration (.d.ts) file containing `declare module 'xivapi-js';`ts(7016)

The error can be suppressed by creating a type declaration file as described, but having type declarations would be even better.

**Comment by kaimoe** [comment]
I haven't been actively developing JS for years and have never touched TS; that said, if you or someone else are willing to add type definitions and ensure they won't cause any issues I will be happy to merge a PR, but can't develop it myself.

**Comment by kaimoe** [comment]
Addressed in #16.
